# Generated by Django 5.0.6 on 2024-07-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.IntegerField(),
        ),
    ]
